apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-bcyq
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/pshivpuj-tenant/devfile-sample-code-with-quarkus/devfile-sample-code-with-quarkus-bcyq@sha256:2cab2416af36ea7f87332d40958a81034aef1ba6fd0a1f97645300e7e42e49f3
        name: my-java-quarkus
        resources: {}
status: {}
